name: Sync Registry
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: env
      run: |
       echo "123.58.241.54 ecr-online.juan.cn" >>/etc/hosts
    - name: Sync From Docker Hun to ecr
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        target_repository: ecr-online.juan.cn/public/nfs-subdir-external-provisioner:v4.0.2
        target_username: ${{ secrets.ECR_USERNAME }}
        target_password: ${{ secrets.ECR_PASSWD }}
   
