name: Sync Registry
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync From Docker Hun to Aliyun
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: k8s.gcr.io/ingress-nginx/controller:v0.44.0
        target_repository: registry.cn-beijing.aliyuncs.com/lvandai/controller:v0.44.0
        target_username: ${{ secrets.ALIYUN_USERNAME }}
        target_password: ${{ secrets.aliyun_passwd }}
    
    steps:
    - name: Sync From Docker Hun to Aliyun
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: docker.io/jettech/kube-webhook-certgen:v1.5.1
        target_repository: registry.cn-beijing.aliyuncs.com/lvandai/kube-webhook-certgen:v1.5.1
        target_username: ${{ secrets.ALIYUN_USERNAME }}
        target_password: ${{ secrets.aliyun_passwd }}
    steps:
    - name: Sync From Docker Hun to Aliyun
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: k8s.gcr.io/defaultbackend-amd64:1.5
        target_repository: registry.cn-beijing.aliyuncs.com/lvandai/defaultbackend-amd64:1.5
        target_username: ${{ secrets.ALIYUN_USERNAME }}
        target_password: ${{ secrets.aliyun_passwd }}
